### ISSUE TITLE
Cannot download repo (over data quota)

### ISSUE THREAD

**Issue by zhanxw** [sczzz3/EHRDiff#1]
I encountered the following errors. Is there an alternative way I can clone this repository? Thanks.

    $ git clone https://github.com/sczzz3/ehrdiff.git
    Cloning into 'ehrdiff'...
    remote: Enumerating objects: 38, done.
    remote: Counting objects: 100% (38/38), done.
    remote: Compressing objects: 100% (28/28), done.
    remote: Total 38 (delta 10), reused 23 (delta 5), pack-reused 0
    Unpacking objects: 100% (38/38), done.
    Downloading proc_data/mimic/mimic1782_test.npy (17 MB)
    Error downloading object: proc_data/mimic/mimic1782_test.npy (65fd665): Smudge error: Error downloading proc_data/mimic/mimic1782_test.npy (65fd665ae23b710136492695061464f54cb3a9c6847c2dc8a1886ab5e89446c3): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
    
    Errors logged to 'XXX/ehrdiff/.git/lfs/logs/20230728T022001.358035108.log'.
    Use `git lfs logs last` to view the log.
    error: external filter git-lfs smudge -- %f failed 2
    error: external filter git-lfs smudge -- %f failed
    fatal: proc_data/mimic/mimic1782_test.npy: smudge filter lfs failed
    warning: Clone succeeded, but checkout failed.
    You can inspect what was checked out with 'git status'
    and retry the checkout with 'git checkout -f HEAD'

**Comment by sczzz3** [comment]
I think it should work now. The data in the repo was removed to avoid this error.

**Comment by zhanxw** [comment]
Thanks. Can you provide instructions on how to generate these binary files (eg mimic1782_test.npy)? Thanks.

**Comment by sczzz3** [comment]
You could follow this [repo](https://github.com/mp2893/medgan/blob/master/process_mimic.ipynb) to generate the binary files. Before that, you need to apply for access to the MIMIC dataset :)
