### ISSUE TITLE
RuntimeError: Mismatch in tensor a and b / mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by madhurimavardhan99** [sczzz3/EHRDiff#2]
The repo [https://github.com/mp2893/medgan/blob/master/process_mimic.ipynb] generates the matrix binary file with 46520 x **1071** dimensions using MIMICS III (https://physionet.org/content/mimiciii-demo/). But this work states 1782 dimensions -- Is there a different dataset or processing script that was used for EHRDIFF? Because of this discrepancy I see the following error:

diffusion_util.py", line 76, in forward
    x = self.block_in(x, t_emb)
  File "/~/.conda/envs/ehrdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/~/ehrdiff-main/diffusion_util.py", line 43, in forward
    h = x + t_emb  
RuntimeError: The size of tensor a (1071) must match the size of tensor b (1782) at non-singleton dimension 1

Upon changing the command line arg as --ehr_dim 1071, I am getting the following error:
/~/ehrdiff-main/diffusion_util.py", line 75, in forward
    t_emb = self.time_embedding(time_steps)
    
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x1070 and 1071x384)

Could you help resolve this issue?

**Comment by sczzz3** [comment]
In the repo [https://github.com/mp2893/medgan/blob/master/process_mimic.ipynb], they processed 'ADMISSIONS.csv' and 'DIAGNOSES_ICD.csv', while in EHRDIFF we extracted diagnosis and procedure ICD-9 code. 
We use one type of sinusoidal position embedding for the time embedding, which requires the dimension to be even. You can try some other kinds of position embeddings e.g. "RandomOrLearnedSinusoidalPosEmb" in [https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/denoising_diffusion_pytorch_1d.py].

**Comment by madhurimavardhan99** [comment]
Thank you for getting back and clarifying. Do you mean that you merged diagnosis and procedure ICD-9 codes in a new file and used the resulting file along with ADMISSIONS.csv with the original post process repo (https://github.com/mp2893/medgan/blob/master/process_mimic.ipynb) to generate the binary matrix file that is used with the EHRDIFF code? When I tried upon using just the procedure icd-9 file (and the admission.csv with the same process_mimics.ipynb) I am getting key errors, and with the merged file (diagnosis_icd and procedure_icd) somehow resulting number of codes come out to be 904 code set (not 1782 codes). Could you please help elaborate your data processing step?

Also, to address the dimension mismatch, does the arg --ehr_dim use the truncated ICD9 code set (EHRDIFF = 1782)? And if so does that not result in dimension mismatch 1024x1781 and 1782x384 error? Thanks for your patience with these questions.

**Comment by Yuanhy1997** [comment]
We use these following codes to truncate the ICD9 code:

```{python}
def convert_to_3digit_icd9(dxStr):
    if dxStr.startswith('E'):
        if len(dxStr) > 4: return dxStr[:4]
        else: return dxStr
    else:
        if len(dxStr) > 3: return dxStr[:3]
        else: return dxStr
```

Hope this will work.
